language: r
r:
  - release
  - devel
cache: packages
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  # sf system requirements
  - sudo apt-get install -y libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  # ncdf4 system requirements
  - sudo apt-get install -y netcdf-bin libnetcdf-dev netcdf-bin

r_github_packages:
  - tidyverse/ggplot2,
  - hadley/testthat,
  - hadley/xml2

after_success:
- Rscript -e 'covr::codecov()'

env:
   global:
     - R_LIBS="http://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - BOOTSTRAP_LATEX=""

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: GXkm1WAyjhaG5VSHCZNHlUylQKt8ZsRtwAXmYyZr4B11eVtCWtYQw+O/fTmAeu8R/IwgTCJnDpqcmCBb+jz5uC6eJv3aXdAxalN0+G7IU/y005KdAowz12G3u13rMlnw0KYHe0tWh8IusycMZWY0xh927IylOJndTn+0hpCEEmg=
